server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/rbac?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: rbac
      password: rbac
      min-idle: 2
      initial-size: 5
      max-active: 8
      max-wait: 60000
  redis:
    database: 1
    host: localhost
    port: 6379
    max-active: 4
    max-wait: -1
    max-idle: 4
    min-idle: 0
    timeout: 20s


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.github.huifer.dao.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: DELETED
      logic-delete-value: 1
      logic-not-delete-value: 0

app:
  version: 1.2.3